import { withDarkIcon } from "@/lib/theme/ui";

export interface Tool {
  id: string;
  titleKey: string;
  descriptionKey: string;
  icon: string;
  href: string;
  category: ToolCategory;
  color: string; // Tailwind icon container — light + dark pairs
}

function icon(light: string) {
  return withDarkIcon(light);
}

export type ToolCategory = "organize" | "convert" | "edit" | "security";

export const TOOLS: Tool[] = [
  // Organize
  {
    id: "merge-pdf",
    titleKey: "tools.mergePdf.title",
    descriptionKey: "tools.mergePdf.description",
    icon: "merge",
    href: "/merge-pdf",
    category: "organize",
    color: icon("bg-indigo-50 text-indigo-600"),
  },
  {
    id: "split-pdf",
    titleKey: "tools.splitPdf.title",
    descriptionKey: "tools.splitPdf.description",
    icon: "cut",
    href: "/split-pdf",
    category: "organize",
    color: icon("bg-rose-50 text-rose-600"),
  },
  {
    id: "split-by-bookmarks",
    titleKey: "tools.splitByBookmarks.title",
    descriptionKey: "tools.splitByBookmarks.description",
    icon: "bookmark_manager",
    href: "/split-by-bookmarks",
    category: "organize",
    color: icon("bg-rose-50 text-rose-700"),
  },
  {
    id: "split-by-size",
    titleKey: "tools.splitBySize.title",
    descriptionKey: "tools.splitBySize.description",
    icon: "storage",
    href: "/split-by-size",
    category: "organize",
    color: icon("bg-rose-50 text-rose-600"),
  },
  {
    id: "merge-alternate",
    titleKey: "tools.mergeAlternate.title",
    descriptionKey: "tools.mergeAlternate.description",
    icon: "layers",
    href: "/merge-alternate",
    category: "organize",
    color: icon("bg-indigo-50 text-indigo-700"),
  },
  {
    id: "organize-pdf",
    titleKey: "tools.organizePdf.title",
    descriptionKey: "tools.organizePdf.description",
    icon: "grid_view",
    href: "/organize-pdf",
    category: "organize",
    color: icon("bg-amber-50 text-amber-600"),
  },
  {
    id: "add-page-numbers",
    titleKey: "tools.addPageNumbers.title",
    descriptionKey: "tools.addPageNumbers.description",
    icon: "format_list_numbered",
    href: "/add-page-numbers",
    category: "organize",
    color: icon("bg-sky-50 text-sky-600"),
  },
  {
    id: "header-footer-pdf",
    titleKey: "tools.headerFooterPdf.title",
    descriptionKey: "tools.headerFooterPdf.description",
    icon: "view_agenda",
    href: "/header-footer-pdf",
    category: "edit",
    color: icon("bg-sky-50 text-sky-700"),
  },
  {
    id: "pdf-workflow",
    titleKey: "tools.pdfWorkflow.title",
    descriptionKey: "tools.pdfWorkflow.description",
    icon: "account_tree",
    href: "/pdf-workflow",
    category: "organize",
    color: icon("bg-blue-50 text-blue-600"),
  },
  {
    id: "compare-pdf",
    titleKey: "tools.comparePdf.title",
    descriptionKey: "tools.comparePdf.description",
    icon: "compare",
    href: "/compare-pdf",
    category: "organize",
    color: icon("bg-indigo-50 text-indigo-600"),
  },
  {
    id: "reverse-pdf",
    titleKey: "tools.reversePdf.title",
    descriptionKey: "tools.reversePdf.description",
    icon: "swap_vert",
    href: "/reverse-pdf",
    category: "organize",
    color: icon("bg-amber-50 text-amber-600"),
  },
  {
    id: "pdf-info",
    titleKey: "tools.pdfInfo.title",
    descriptionKey: "tools.pdfInfo.description",
    icon: "info",
    href: "/pdf-info",
    category: "organize",
    color: icon("bg-blue-50 text-blue-600"),
  },
  {
    id: "remove-blank-pages",
    titleKey: "tools.removeBlankPages.title",
    descriptionKey: "tools.removeBlankPages.description",
    icon: "filter_none",
    href: "/remove-blank-pages",
    category: "organize",
    color: icon("bg-sky-50 text-sky-600"),
  },
  {
    id: "duplicate-pages",
    titleKey: "tools.duplicatePages.title",
    descriptionKey: "tools.duplicatePages.description",
    icon: "content_copy",
    href: "/duplicate-pages",
    category: "organize",
    color: icon("bg-indigo-50 text-indigo-600"),
  },
  {
    id: "extract-pages",
    titleKey: "tools.extractPages.title",
    descriptionKey: "tools.extractPages.description",
    icon: "file_export",
    href: "/extract-pages",
    category: "organize",
    color: icon("bg-emerald-50 text-emerald-600"),
  },
  {
    id: "bookmarks-pdf",
    titleKey: "tools.bookmarksPdf.title",
    descriptionKey: "tools.bookmarksPdf.description",
    icon: "bookmark_add",
    href: "/bookmarks-pdf",
    category: "organize",
    color: icon("bg-amber-50 text-amber-600"),
  },
  // Convert
  {
    id: "pdf-to-jpg",
    titleKey: "tools.pdfToJpg.title",
    descriptionKey: "tools.pdfToJpg.description",
    icon: "image",
    href: "/pdf-to-jpg",
    category: "convert",
    color: icon("bg-orange-50 text-orange-600"),
  },
  {
    id: "jpg-to-pdf",
    titleKey: "tools.jpgToPdf.title",
    descriptionKey: "tools.jpgToPdf.description",
    icon: "add_photo_alternate",
    href: "/jpg-to-pdf",
    category: "convert",
    color: icon("bg-fuchsia-50 text-fuchsia-600"),
  },
  {
    id: "pdf-to-word",
    titleKey: "tools.pdfToWord.title",
    descriptionKey: "tools.pdfToWord.description",
    icon: "description",
    href: "/pdf-to-word",
    category: "convert",
    color: icon("bg-blue-50 text-blue-600"),
  },
  {
    id: "word-to-pdf",
    titleKey: "tools.wordToPdf.title",
    descriptionKey: "tools.wordToPdf.description",
    icon: "description",
    href: "/word-to-pdf",
    category: "convert",
    color: icon("bg-blue-50 text-blue-700"),
  },
  {
    id: "pdf-to-powerpoint",
    titleKey: "tools.pdfToPowerpoint.title",
    descriptionKey: "tools.pdfToPowerpoint.description",
    icon: "slideshow",
    href: "/pdf-to-powerpoint",
    category: "convert",
    color: icon("bg-orange-50 text-orange-700"),
  },
  {
    id: "powerpoint-to-pdf",
    titleKey: "tools.powerpointToPdf.title",
    descriptionKey: "tools.powerpointToPdf.description",
    icon: "slideshow",
    href: "/powerpoint-to-pdf",
    category: "convert",
    color: icon("bg-orange-50 text-orange-800"),
  },
  {
    id: "website-to-pdf",
    titleKey: "tools.websiteToPdf.title",
    descriptionKey: "tools.websiteToPdf.description",
    icon: "language",
    href: "/website-to-pdf",
    category: "convert",
    color: icon("bg-stone-50 text-stone-600"),
  },
  {
    id: "pdf-to-excel",
    titleKey: "tools.pdfToExcel.title",
    descriptionKey: "tools.pdfToExcel.description",
    icon: "table_chart",
    href: "/pdf-to-excel",
    category: "convert",
    color: icon("bg-green-50 text-green-600"),
  },
  {
    id: "excel-to-pdf",
    titleKey: "tools.excelToPdf.title",
    descriptionKey: "tools.excelToPdf.description",
    icon: "table_view",
    href: "/excel-to-pdf",
    category: "convert",
    color: icon("bg-green-50 text-green-700"),
  },
  {
    id: "extract-images-pdf",
    titleKey: "tools.extractImagesPdf.title",
    descriptionKey: "tools.extractImagesPdf.description",
    icon: "photo_library",
    href: "/extract-images-pdf",
    category: "convert",
    color: icon("bg-amber-50 text-amber-600"),
  },
  {
    id: "pdf-to-pdfa",
    titleKey: "tools.pdfToPdfa.title",
    descriptionKey: "tools.pdfToPdfa.description",
    icon: "verified",
    href: "/pdf-to-pdfa",
    category: "convert",
    color: icon("bg-slate-50 text-slate-600"),
  },
  {
    id: "pdfa-preflight",
    titleKey: "tools.pdfaPreflight.title",
    descriptionKey: "tools.pdfaPreflight.description",
    icon: "fact_check",
    href: "/pdfa-preflight",
    category: "convert",
    color: icon("bg-slate-50 text-slate-700"),
  },
  {
    id: "pdf-to-pdfa-server",
    titleKey: "tools.pdfToPdfaServer.title",
    descriptionKey: "tools.pdfToPdfaServer.description",
    icon: "verified",
    href: "/pdf-to-pdfa-server",
    category: "convert",
    color: icon("bg-blue-50 text-blue-800"),
  },
  {
    id: "pdf-to-png",
    titleKey: "tools.pdfToPng.title",
    descriptionKey: "tools.pdfToPng.description",
    icon: "image",
    href: "/pdf-to-png",
    category: "convert",
    color: icon("bg-violet-50 text-violet-600"),
  },
  {
    id: "png-to-pdf",
    titleKey: "tools.pngToPdf.title",
    descriptionKey: "tools.pngToPdf.description",
    icon: "picture_as_pdf",
    href: "/png-to-pdf",
    category: "convert",
    color: icon("bg-indigo-50 text-indigo-600"),
  },
  {
    id: "webp-to-pdf",
    titleKey: "tools.webpToPdf.title",
    descriptionKey: "tools.webpToPdf.description",
    icon: "image",
    href: "/webp-to-pdf",
    category: "convert",
    color: icon("bg-lime-50 text-lime-600"),
  },
  {
    id: "extract-text-pdf",
    titleKey: "tools.extractTextPdf.title",
    descriptionKey: "tools.extractTextPdf.description",
    icon: "text_snippet",
    href: "/extract-text-pdf",
    category: "convert",
    color: icon("bg-slate-50 text-slate-600"),
  },
  {
    id: "text-to-pdf",
    titleKey: "tools.textToPdf.title",
    descriptionKey: "tools.textToPdf.description",
    icon: "article",
    href: "/text-to-pdf",
    category: "convert",
    color: icon("bg-stone-50 text-stone-600"),
  },
  // Edit
  {
    id: "compress-pdf",
    titleKey: "tools.compressPdf.title",
    descriptionKey: "tools.compressPdf.description",
    icon: "compress",
    href: "/compress-pdf",
    category: "edit",
    color: icon("bg-emerald-50 text-emerald-600"),
  },
  {
    id: "rotate-pdf",
    titleKey: "tools.rotatePdf.title",
    descriptionKey: "tools.rotatePdf.description",
    icon: "rotate_right",
    href: "/rotate-pdf",
    category: "edit",
    color: icon("bg-purple-50 text-purple-600"),
  },
  {
    id: "auto-rotate-pdf",
    titleKey: "tools.autoRotatePdf.title",
    descriptionKey: "tools.autoRotatePdf.description",
    icon: "screen_rotation",
    href: "/auto-rotate-pdf",
    category: "edit",
    color: icon("bg-purple-50 text-purple-700"),
  },
  {
    id: "extract-attachments-pdf",
    titleKey: "tools.extractAttachmentsPdf.title",
    descriptionKey: "tools.extractAttachmentsPdf.description",
    icon: "attach_file",
    href: "/extract-attachments-pdf",
    category: "convert",
    color: icon("bg-amber-50 text-amber-700"),
  },
  {
    id: "tiff-to-pdf",
    titleKey: "tools.tiffToPdf.title",
    descriptionKey: "tools.tiffToPdf.description",
    icon: "image",
    href: "/tiff-to-pdf",
    category: "convert",
    color: icon("bg-cyan-50 text-cyan-600"),
  },
  {
    id: "visual-diff-pdf",
    titleKey: "tools.visualDiffPdf.title",
    descriptionKey: "tools.visualDiffPdf.description",
    icon: "difference",
    href: "/visual-diff-pdf",
    category: "organize",
    color: icon("bg-rose-50 text-rose-700"),
  },
  {
    id: "batch-workflow",
    titleKey: "tools.batchWorkflow.title",
    descriptionKey: "tools.batchWorkflow.description",
    icon: "account_tree",
    href: "/batch-workflow",
    category: "organize",
    color: icon("bg-blue-50 text-blue-800"),
  },
  {
    id: "add-attachments-pdf",
    titleKey: "tools.addAttachmentsPdf.title",
    descriptionKey: "tools.addAttachmentsPdf.description",
    icon: "attachment",
    href: "/add-attachments-pdf",
    category: "edit",
    color: icon("bg-teal-50 text-teal-700"),
  },
  {
    id: "heic-to-pdf",
    titleKey: "tools.heicToPdf.title",
    descriptionKey: "tools.heicToPdf.description",
    icon: "photo_camera",
    href: "/heic-to-pdf",
    category: "convert",
    color: icon("bg-violet-50 text-violet-600"),
  },
  {
    id: "bates-numbering-pdf",
    titleKey: "tools.batesNumberingPdf.title",
    descriptionKey: "tools.batesNumberingPdf.description",
    icon: "tag",
    href: "/bates-numbering-pdf",
    category: "edit",
    color: icon("bg-slate-50 text-slate-700"),
  },
  {
    id: "pdf-to-html",
    titleKey: "tools.pdfToHtml.title",
    descriptionKey: "tools.pdfToHtml.description",
    icon: "code",
    href: "/pdf-to-html",
    category: "convert",
    color: icon("bg-orange-50 text-orange-600"),
  },
  {
    id: "split-by-text",
    titleKey: "tools.splitByText.title",
    descriptionKey: "tools.splitByText.description",
    icon: "text_fields",
    href: "/split-by-text",
    category: "organize",
    color: icon("bg-indigo-50 text-indigo-600"),
  },
  {
    id: "add-links-pdf",
    titleKey: "tools.addLinksPdf.title",
    descriptionKey: "tools.addLinksPdf.description",
    icon: "link",
    href: "/add-links-pdf",
    category: "edit",
    color: icon("bg-blue-50 text-blue-600"),
  },
  {
    id: "watermark-pdf",
    titleKey: "tools.watermarkPdf.title",
    descriptionKey: "tools.watermarkPdf.description",
    icon: "water",
    href: "/watermark-pdf",
    category: "edit",
    color: icon("bg-cyan-50 text-cyan-600"),
  },
  {
    id: "sign-pdf",
    titleKey: "tools.signPdf.title",
    descriptionKey: "tools.signPdf.description",
    icon: "draw",
    href: "/sign-pdf",
    category: "edit",
    color: icon("bg-pink-50 text-pink-600"),
  },
  {
    id: "highlight-pdf",
    titleKey: "tools.highlightPdf.title",
    descriptionKey: "tools.highlightPdf.description",
    icon: "draw",
    href: "/highlight-pdf",
    category: "edit",
    color: icon("bg-yellow-50 text-yellow-600"),
  },
  {
    id: "stamp-pdf",
    titleKey: "tools.stampPdf.title",
    descriptionKey: "tools.stampPdf.description",
    icon: "approval",
    href: "/stamp-pdf",
    category: "edit",
    color: icon("bg-teal-50 text-teal-600"),
  },
  {
    id: "crop-pdf",
    titleKey: "tools.cropPdf.title",
    descriptionKey: "tools.cropPdf.description",
    icon: "crop",
    href: "/crop-pdf",
    category: "edit",
    color: icon("bg-lime-50 text-lime-600"),
  },
  {
    id: "add-padding-pdf",
    titleKey: "tools.addPaddingPdf.title",
    descriptionKey: "tools.addPaddingPdf.description",
    icon: "border_outer",
    href: "/add-padding-pdf",
    category: "edit",
    color: icon("bg-slate-100 text-slate-700"),
  },
  {
    id: "ocr-pdf",
    titleKey: "tools.ocrPdf.title",
    descriptionKey: "tools.ocrPdf.description",
    icon: "document_scanner",
    href: "/ocr-pdf",
    category: "edit",
    color: icon("bg-violet-50 text-violet-600"),
  },
  {
    id: "redact-pdf",
    titleKey: "tools.redactPdf.title",
    descriptionKey: "tools.redactPdf.description",
    icon: "visibility_off",
    href: "/redact-pdf",
    category: "edit",
    color: icon("bg-neutral-50 text-neutral-600"),
  },
  {
    id: "edit-metadata-pdf",
    titleKey: "tools.editMetadataPdf.title",
    descriptionKey: "tools.editMetadataPdf.description",
    icon: "info",
    href: "/edit-metadata-pdf",
    category: "edit",
    color: icon("bg-zinc-50 text-zinc-600"),
  },
  {
    id: "repair-pdf",
    titleKey: "tools.repairPdf.title",
    descriptionKey: "tools.repairPdf.description",
    icon: "build",
    href: "/repair-pdf",
    category: "edit",
    color: icon("bg-orange-50 text-orange-600"),
  },
  {
    id: "fill-pdf-forms",
    titleKey: "tools.fillPdfForms.title",
    descriptionKey: "tools.fillPdfForms.description",
    icon: "edit_note",
    href: "/fill-pdf-forms",
    category: "edit",
    color: icon("bg-cyan-50 text-cyan-600"),
  },
  {
    id: "grayscale-pdf",
    titleKey: "tools.grayscalePdf.title",
    descriptionKey: "tools.grayscalePdf.description",
    icon: "tonality",
    href: "/grayscale-pdf",
    category: "edit",
    color: icon("bg-neutral-50 text-neutral-600"),
  },
  {
    id: "invert-pdf",
    titleKey: "tools.invertPdf.title",
    descriptionKey: "tools.invertPdf.description",
    icon: "invert_colors",
    href: "/invert-pdf",
    category: "edit",
    color: icon("bg-purple-50 text-purple-600"),
  },
  {
    id: "flatten-pdf",
    titleKey: "tools.flattenPdf.title",
    descriptionKey: "tools.flattenPdf.description",
    icon: "layers",
    href: "/flatten-pdf",
    category: "edit",
    color: icon("bg-teal-50 text-teal-600"),
  },
  {
    id: "remove-annotations",
    titleKey: "tools.removeAnnotations.title",
    descriptionKey: "tools.removeAnnotations.description",
    icon: "comments_disabled",
    href: "/remove-annotations",
    category: "edit",
    color: icon("bg-rose-50 text-rose-600"),
  },
  {
    id: "add-image-pdf",
    titleKey: "tools.addImagePdf.title",
    descriptionKey: "tools.addImagePdf.description",
    icon: "add_photo_alternate",
    href: "/add-image-pdf",
    category: "edit",
    color: icon("bg-pink-50 text-pink-600"),
  },
  {
    id: "resize-pdf",
    titleKey: "tools.resizePdf.title",
    descriptionKey: "tools.resizePdf.description",
    icon: "aspect_ratio",
    href: "/resize-pdf",
    category: "edit",
    color: icon("bg-cyan-50 text-cyan-600"),
  },
  {
    id: "n-up-pdf",
    titleKey: "tools.nUpPdf.title",
    descriptionKey: "tools.nUpPdf.description",
    icon: "grid_view",
    href: "/n-up-pdf",
    category: "organize",
    color: icon("bg-violet-50 text-violet-600"),
  },
  {
    id: "booklet-pdf",
    titleKey: "tools.bookletPdf.title",
    descriptionKey: "tools.bookletPdf.description",
    icon: "menu_book",
    href: "/booklet-pdf",
    category: "organize",
    color: icon("bg-amber-50 text-amber-600"),
  },
  {
    id: "sanitize-pdf",
    titleKey: "tools.sanitizePdf.title",
    descriptionKey: "tools.sanitizePdf.description",
    icon: "cleaning_services",
    href: "/sanitize-pdf",
    category: "security",
    color: icon("bg-slate-50 text-slate-600"),
  },
  {
    id: "compress-images-pdf",
    titleKey: "tools.compressImagesPdf.title",
    descriptionKey: "tools.compressImagesPdf.description",
    icon: "photo_size_select_small",
    href: "/compress-images-pdf",
    category: "edit",
    color: icon("bg-emerald-50 text-emerald-600"),
  },
  {
    id: "csv-to-pdf",
    titleKey: "tools.csvToPdf.title",
    descriptionKey: "tools.csvToPdf.description",
    icon: "table_chart",
    href: "/csv-to-pdf",
    category: "convert",
    color: icon("bg-green-50 text-green-600"),
  },
  {
    id: "pdf-to-csv",
    titleKey: "tools.pdfToCsv.title",
    descriptionKey: "tools.pdfToCsv.description",
    icon: "table_view",
    href: "/pdf-to-csv",
    category: "convert",
    color: icon("bg-green-50 text-green-700"),
  },
  {
    id: "pdf-summary",
    titleKey: "tools.pdfSummary.title",
    descriptionKey: "tools.pdfSummary.description",
    icon: "auto_awesome",
    href: "/pdf-summary",
    category: "convert",
    color: icon("bg-violet-50 text-violet-600"),
  },
  {
    id: "create-pdf-form",
    titleKey: "tools.createPdfForm.title",
    descriptionKey: "tools.createPdfForm.description",
    icon: "edit_note",
    href: "/create-pdf-form",
    category: "edit",
    color: icon("bg-cyan-50 text-cyan-600"),
  },
  {
    id: "markdown-to-pdf",
    titleKey: "tools.markdownToPdf.title",
    descriptionKey: "tools.markdownToPdf.description",
    icon: "markdown",
    href: "/markdown-to-pdf",
    category: "convert",
    color: icon("bg-slate-50 text-slate-600"),
  },
  {
    id: "bmp-to-pdf",
    titleKey: "tools.bmpToPdf.title",
    descriptionKey: "tools.bmpToPdf.description",
    icon: "image",
    href: "/bmp-to-pdf",
    category: "convert",
    color: icon("bg-fuchsia-50 text-fuchsia-600"),
  },
  {
    id: "gif-to-pdf",
    titleKey: "tools.gifToPdf.title",
    descriptionKey: "tools.gifToPdf.description",
    icon: "gif",
    href: "/gif-to-pdf",
    category: "convert",
    color: icon("bg-pink-50 text-pink-600"),
  },
  {
    id: "insert-pages-pdf",
    titleKey: "tools.insertPagesPdf.title",
    descriptionKey: "tools.insertPagesPdf.description",
    icon: "login",
    href: "/insert-pages-pdf",
    category: "organize",
    color: icon("bg-indigo-50 text-indigo-600"),
  },
  {
    id: "overlay-pdf",
    titleKey: "tools.overlayPdf.title",
    descriptionKey: "tools.overlayPdf.description",
    icon: "layers",
    href: "/overlay-pdf",
    category: "edit",
    color: icon("bg-teal-50 text-teal-600"),
  },
  {
    id: "pdf-to-markdown",
    titleKey: "tools.pdfToMarkdown.title",
    descriptionKey: "tools.pdfToMarkdown.description",
    icon: "markdown",
    href: "/pdf-to-markdown",
    category: "convert",
    color: icon("bg-stone-50 text-stone-600"),
  },
  {
    id: "json-to-pdf",
    titleKey: "tools.jsonToPdf.title",
    descriptionKey: "tools.jsonToPdf.description",
    icon: "data_object",
    href: "/json-to-pdf",
    category: "convert",
    color: icon("bg-amber-50 text-amber-600"),
  },
  {
    id: "add-blank-pages",
    titleKey: "tools.addBlankPages.title",
    descriptionKey: "tools.addBlankPages.description",
    icon: "note_add",
    href: "/add-blank-pages",
    category: "organize",
    color: icon("bg-sky-50 text-sky-600"),
  },
  {
    id: "shuffle-pdf",
    titleKey: "tools.shufflePdf.title",
    descriptionKey: "tools.shufflePdf.description",
    icon: "shuffle",
    href: "/shuffle-pdf",
    category: "organize",
    color: icon("bg-purple-50 text-purple-600"),
  },
  {
    id: "mirror-pdf",
    titleKey: "tools.mirrorPdf.title",
    descriptionKey: "tools.mirrorPdf.description",
    icon: "flip",
    href: "/mirror-pdf",
    category: "edit",
    color: icon("bg-rose-50 text-rose-600"),
  },
  {
    id: "posterize-pdf",
    titleKey: "tools.posterizePdf.title",
    descriptionKey: "tools.posterizePdf.description",
    icon: "grid_on",
    href: "/posterize-pdf",
    category: "organize",
    color: icon("bg-orange-50 text-orange-600"),
  },
  {
    id: "fit-to-page-pdf",
    titleKey: "tools.fitToPagePdf.title",
    descriptionKey: "tools.fitToPagePdf.description",
    icon: "fit_screen",
    href: "/fit-to-page-pdf",
    category: "edit",
    color: icon("bg-cyan-50 text-cyan-700"),
  },
  {
    id: "page-labels-pdf",
    titleKey: "tools.pageLabelsPdf.title",
    descriptionKey: "tools.pageLabelsPdf.description",
    icon: "label",
    href: "/page-labels-pdf",
    category: "edit",
    color: icon("bg-blue-50 text-blue-600"),
  },
  {
    id: "pdf-to-json",
    titleKey: "tools.pdfToJson.title",
    descriptionKey: "tools.pdfToJson.description",
    icon: "data_object",
    href: "/pdf-to-json",
    category: "convert",
    color: icon("bg-yellow-50 text-yellow-700"),
  },
  {
    id: "tile-pdf",
    titleKey: "tools.tilePdf.title",
    descriptionKey: "tools.tilePdf.description",
    icon: "view_module",
    href: "/tile-pdf",
    category: "organize",
    color: icon("bg-lime-50 text-lime-600"),
  },
  {
    id: "replace-pages-pdf",
    titleKey: "tools.replacePagesPdf.title",
    descriptionKey: "tools.replacePagesPdf.description",
    icon: "sync",
    href: "/replace-pages-pdf",
    category: "organize",
    color: icon("bg-indigo-50 text-indigo-700"),
  },
  {
    id: "add-background-pdf",
    titleKey: "tools.addBackgroundPdf.title",
    descriptionKey: "tools.addBackgroundPdf.description",
    icon: "format_color_fill",
    href: "/add-background-pdf",
    category: "edit",
    color: icon("bg-emerald-50 text-emerald-600"),
  },
  {
    id: "pdf-validator",
    titleKey: "tools.pdfValidator.title",
    descriptionKey: "tools.pdfValidator.description",
    icon: "fact_check",
    href: "/pdf-validator",
    category: "organize",
    color: icon("bg-slate-50 text-slate-700"),
  },
  {
    id: "xml-to-pdf",
    titleKey: "tools.xmlToPdf.title",
    descriptionKey: "tools.xmlToPdf.description",
    icon: "code",
    href: "/xml-to-pdf",
    category: "convert",
    color: icon("bg-orange-50 text-orange-700"),
  },
  {
    id: "split-even-odd",
    titleKey: "tools.splitEvenOdd.title",
    descriptionKey: "tools.splitEvenOdd.description",
    icon: "filter_1",
    href: "/split-even-odd",
    category: "organize",
    color: icon("bg-rose-50 text-rose-700"),
  },
  {
    id: "export-bookmarks-pdf",
    titleKey: "tools.exportBookmarksPdf.title",
    descriptionKey: "tools.exportBookmarksPdf.description",
    icon: "bookmark",
    href: "/export-bookmarks-pdf",
    category: "convert",
    color: icon("bg-amber-50 text-amber-700"),
  },
  {
    id: "qr-code-pdf",
    titleKey: "tools.qrCodePdf.title",
    descriptionKey: "tools.qrCodePdf.description",
    icon: "qr_code_2",
    href: "/qr-code-pdf",
    category: "edit",
    color: icon("bg-neutral-50 text-neutral-700"),
  },
  {
    id: "invoice-pdf",
    titleKey: "tools.invoicePdf.title",
    descriptionKey: "tools.invoicePdf.description",
    icon: "receipt_long",
    href: "/invoice-pdf",
    category: "convert",
    color: icon("bg-teal-50 text-teal-700"),
  },
  {
    id: "linearize-pdf",
    titleKey: "tools.linearizePdf.title",
    descriptionKey: "tools.linearizePdf.description",
    icon: "speed",
    href: "/linearize-pdf",
    category: "edit",
    color: icon("bg-blue-50 text-blue-700"),
  },
  {
    id: "duplicate-range-pdf",
    titleKey: "tools.duplicateRangePdf.title",
    descriptionKey: "tools.duplicateRangePdf.description",
    icon: "content_copy",
    href: "/duplicate-range-pdf",
    category: "organize",
    color: icon("bg-pink-50 text-pink-700"),
  },
  {
    id: "svg-to-pdf",
    titleKey: "tools.svgToPdf.title",
    descriptionKey: "tools.svgToPdf.description",
    icon: "draw",
    href: "/svg-to-pdf",
    category: "convert",
    color: icon("bg-indigo-50 text-indigo-800"),
  },
  {
    id: "sort-pages-size-pdf",
    titleKey: "tools.sortPagesSizePdf.title",
    descriptionKey: "tools.sortPagesSizePdf.description",
    icon: "sort",
    href: "/sort-pages-size-pdf",
    category: "organize",
    color: icon("bg-violet-50 text-violet-700"),
  },
  {
    id: "pdf-to-pdfa-3",
    titleKey: "tools.pdfToPdfa-3.title",
    descriptionKey: "tools.pdfToPdfa-3.description",
    icon: "verified",
    href: "/pdf-to-pdfa-3",
    category: "convert",
    color: icon("bg-slate-50 text-slate-800"),
  },
  {
    id: "combine-text-pdf",
    titleKey: "tools.combineTextPdf.title",
    descriptionKey: "tools.combineTextPdf.description",
    icon: "article",
    href: "/combine-text-pdf",
    category: "convert",
    color: icon("bg-stone-50 text-stone-700"),
  },
  {
    id: "remove-metadata-pdf",
    titleKey: "tools.removeMetadataPdf.title",
    descriptionKey: "tools.removeMetadataPdf.description",
    icon: "delete_forever",
    href: "/remove-metadata-pdf",
    category: "security",
    color: icon("bg-red-50 text-red-700"),
  },
  {
    id: "split-every-n-pages",
    titleKey: "tools.splitEveryNPages.title",
    descriptionKey: "tools.splitEveryNPages.description",
    icon: "filter_2",
    href: "/split-every-n-pages",
    category: "organize",
    color: icon("bg-rose-50 text-rose-600"),
  },

  // Security
  {
    id: "protect-pdf",
    titleKey: "tools.protectPdf.title",
    descriptionKey: "tools.protectPdf.description",
    icon: "lock",
    href: "/protect-pdf",
    category: "security",
    color: icon("bg-red-50 text-red-600"),
  },
  {
    id: "unlock-pdf",
    titleKey: "tools.unlockPdf.title",
    descriptionKey: "tools.unlockPdf.description",
    icon: "lock_open",
    href: "/unlock-pdf",
    category: "security",
    color: icon("bg-green-50 text-green-600"),
  },
  {
    id: "verify-signature-pdf",
    titleKey: "tools.verifySignaturePdf.title",
    descriptionKey: "tools.verifySignaturePdf.description",
    icon: "verified_user",
    href: "/verify-signature-pdf",
    category: "security",
    color: icon("bg-red-50 text-red-600"),
  },
];

export const CATEGORY_KEYS: { id: ToolCategory | "all"; labelKey: string }[] = [
  { id: "all", labelKey: "categories.all" },
  { id: "organize", labelKey: "categories.organize" },
  { id: "convert", labelKey: "categories.convert" },
  { id: "edit", labelKey: "categories.edit" },
  { id: "security", labelKey: "categories.security" },
];

export const CATEGORY_ORDER: ToolCategory[] = ["organize", "convert", "edit", "security"];

// Keep backward-compatible export name
export const CATEGORIES = CATEGORY_KEYS;
