import { withDarkIcon } from "@/lib/theme/ui";

export interface Tool {
  id: string;
  titleKey: string;
  descriptionKey: string;
  icon: string;
  href: string;
  category: ToolCategory;
  color: string; // Tailwind icon container — light + dark pairs
}

function icon(light: string) {
  return withDarkIcon(light);
}

export type ToolCategory = "organize" | "convert" | "edit" | "security";

export const TOOLS: Tool[] = [
  // Organize
  {
    id: "merge-pdf",
    titleKey: "tools.mergePdf.title",
    descriptionKey: "tools.mergePdf.description",
    icon: "merge",
    href: "/merge-pdf",
    category: "organize",
    color: icon("bg-indigo-50 text-indigo-600"),
  },
  {
    id: "split-pdf",
    titleKey: "tools.splitPdf.title",
    descriptionKey: "tools.splitPdf.description",
    icon: "cut",
    href: "/split-pdf",
    category: "organize",
    color: icon("bg-rose-50 text-rose-600"),
  },
  {
    id: "organize-pdf",
    titleKey: "tools.organizePdf.title",
    descriptionKey: "tools.organizePdf.description",
    icon: "grid_view",
    href: "/organize-pdf",
    category: "organize",
    color: icon("bg-amber-50 text-amber-600"),
  },
  {
    id: "add-page-numbers",
    titleKey: "tools.addPageNumbers.title",
    descriptionKey: "tools.addPageNumbers.description",
    icon: "format_list_numbered",
    href: "/add-page-numbers",
    category: "organize",
    color: icon("bg-sky-50 text-sky-600"),
  },
  {
    id: "pdf-workflow",
    titleKey: "tools.pdfWorkflow.title",
    descriptionKey: "tools.pdfWorkflow.description",
    icon: "account_tree",
    href: "/pdf-workflow",
    category: "organize",
    color: icon("bg-blue-50 text-blue-600"),
  },
  {
    id: "compare-pdf",
    titleKey: "tools.comparePdf.title",
    descriptionKey: "tools.comparePdf.description",
    icon: "compare",
    href: "/compare-pdf",
    category: "organize",
    color: icon("bg-indigo-50 text-indigo-600"),
  },
  {
    id: "reverse-pdf",
    titleKey: "tools.reversePdf.title",
    descriptionKey: "tools.reversePdf.description",
    icon: "swap_vert",
    href: "/reverse-pdf",
    category: "organize",
    color: icon("bg-amber-50 text-amber-600"),
  },
  {
    id: "pdf-info",
    titleKey: "tools.pdfInfo.title",
    descriptionKey: "tools.pdfInfo.description",
    icon: "info",
    href: "/pdf-info",
    category: "organize",
    color: icon("bg-blue-50 text-blue-600"),
  },
  {
    id: "remove-blank-pages",
    titleKey: "tools.removeBlankPages.title",
    descriptionKey: "tools.removeBlankPages.description",
    icon: "filter_none",
    href: "/remove-blank-pages",
    category: "organize",
    color: icon("bg-sky-50 text-sky-600"),
  },
  {
    id: "duplicate-pages",
    titleKey: "tools.duplicatePages.title",
    descriptionKey: "tools.duplicatePages.description",
    icon: "content_copy",
    href: "/duplicate-pages",
    category: "organize",
    color: icon("bg-indigo-50 text-indigo-600"),
  },
  {
    id: "extract-pages",
    titleKey: "tools.extractPages.title",
    descriptionKey: "tools.extractPages.description",
    icon: "file_export",
    href: "/extract-pages",
    category: "organize",
    color: icon("bg-emerald-50 text-emerald-600"),
  },
  // Convert
  {
    id: "pdf-to-jpg",
    titleKey: "tools.pdfToJpg.title",
    descriptionKey: "tools.pdfToJpg.description",
    icon: "image",
    href: "/pdf-to-jpg",
    category: "convert",
    color: icon("bg-orange-50 text-orange-600"),
  },
  {
    id: "jpg-to-pdf",
    titleKey: "tools.jpgToPdf.title",
    descriptionKey: "tools.jpgToPdf.description",
    icon: "add_photo_alternate",
    href: "/jpg-to-pdf",
    category: "convert",
    color: icon("bg-fuchsia-50 text-fuchsia-600"),
  },
  {
    id: "pdf-to-word",
    titleKey: "tools.pdfToWord.title",
    descriptionKey: "tools.pdfToWord.description",
    icon: "description",
    href: "/pdf-to-word",
    category: "convert",
    color: icon("bg-blue-50 text-blue-600"),
  },
  {
    id: "website-to-pdf",
    titleKey: "tools.websiteToPdf.title",
    descriptionKey: "tools.websiteToPdf.description",
    icon: "language",
    href: "/website-to-pdf",
    category: "convert",
    color: icon("bg-stone-50 text-stone-600"),
  },
  {
    id: "pdf-to-excel",
    titleKey: "tools.pdfToExcel.title",
    descriptionKey: "tools.pdfToExcel.description",
    icon: "table_chart",
    href: "/pdf-to-excel",
    category: "convert",
    color: icon("bg-green-50 text-green-600"),
  },
  {
    id: "extract-images-pdf",
    titleKey: "tools.extractImagesPdf.title",
    descriptionKey: "tools.extractImagesPdf.description",
    icon: "photo_library",
    href: "/extract-images-pdf",
    category: "convert",
    color: icon("bg-amber-50 text-amber-600"),
  },
  {
    id: "pdf-to-pdfa",
    titleKey: "tools.pdfToPdfa.title",
    descriptionKey: "tools.pdfToPdfa.description",
    icon: "verified",
    href: "/pdf-to-pdfa",
    category: "convert",
    color: icon("bg-slate-50 text-slate-600"),
  },
  {
    id: "pdf-to-png",
    titleKey: "tools.pdfToPng.title",
    descriptionKey: "tools.pdfToPng.description",
    icon: "image",
    href: "/pdf-to-png",
    category: "convert",
    color: icon("bg-violet-50 text-violet-600"),
  },
  {
    id: "png-to-pdf",
    titleKey: "tools.pngToPdf.title",
    descriptionKey: "tools.pngToPdf.description",
    icon: "picture_as_pdf",
    href: "/png-to-pdf",
    category: "convert",
    color: icon("bg-indigo-50 text-indigo-600"),
  },
  {
    id: "extract-text-pdf",
    titleKey: "tools.extractTextPdf.title",
    descriptionKey: "tools.extractTextPdf.description",
    icon: "text_snippet",
    href: "/extract-text-pdf",
    category: "convert",
    color: icon("bg-slate-50 text-slate-600"),
  },
  // Edit
  {
    id: "compress-pdf",
    titleKey: "tools.compressPdf.title",
    descriptionKey: "tools.compressPdf.description",
    icon: "compress",
    href: "/compress-pdf",
    category: "edit",
    color: icon("bg-emerald-50 text-emerald-600"),
  },
  {
    id: "rotate-pdf",
    titleKey: "tools.rotatePdf.title",
    descriptionKey: "tools.rotatePdf.description",
    icon: "rotate_right",
    href: "/rotate-pdf",
    category: "edit",
    color: icon("bg-purple-50 text-purple-600"),
  },
  {
    id: "watermark-pdf",
    titleKey: "tools.watermarkPdf.title",
    descriptionKey: "tools.watermarkPdf.description",
    icon: "water",
    href: "/watermark-pdf",
    category: "edit",
    color: icon("bg-cyan-50 text-cyan-600"),
  },
  {
    id: "sign-pdf",
    titleKey: "tools.signPdf.title",
    descriptionKey: "tools.signPdf.description",
    icon: "draw",
    href: "/sign-pdf",
    category: "edit",
    color: icon("bg-pink-50 text-pink-600"),
  },
  {
    id: "highlight-pdf",
    titleKey: "tools.highlightPdf.title",
    descriptionKey: "tools.highlightPdf.description",
    icon: "draw",
    href: "/highlight-pdf",
    category: "edit",
    color: icon("bg-yellow-50 text-yellow-600"),
  },
  {
    id: "stamp-pdf",
    titleKey: "tools.stampPdf.title",
    descriptionKey: "tools.stampPdf.description",
    icon: "approval",
    href: "/stamp-pdf",
    category: "edit",
    color: icon("bg-teal-50 text-teal-600"),
  },
  {
    id: "crop-pdf",
    titleKey: "tools.cropPdf.title",
    descriptionKey: "tools.cropPdf.description",
    icon: "crop",
    href: "/crop-pdf",
    category: "edit",
    color: icon("bg-lime-50 text-lime-600"),
  },
  {
    id: "add-padding-pdf",
    titleKey: "tools.addPaddingPdf.title",
    descriptionKey: "tools.addPaddingPdf.description",
    icon: "border_outer",
    href: "/add-padding-pdf",
    category: "edit",
    color: icon("bg-slate-100 text-slate-700"),
  },
  {
    id: "ocr-pdf",
    titleKey: "tools.ocrPdf.title",
    descriptionKey: "tools.ocrPdf.description",
    icon: "document_scanner",
    href: "/ocr-pdf",
    category: "edit",
    color: icon("bg-violet-50 text-violet-600"),
  },
  {
    id: "redact-pdf",
    titleKey: "tools.redactPdf.title",
    descriptionKey: "tools.redactPdf.description",
    icon: "visibility_off",
    href: "/redact-pdf",
    category: "edit",
    color: icon("bg-neutral-50 text-neutral-600"),
  },
  {
    id: "edit-metadata-pdf",
    titleKey: "tools.editMetadataPdf.title",
    descriptionKey: "tools.editMetadataPdf.description",
    icon: "info",
    href: "/edit-metadata-pdf",
    category: "edit",
    color: icon("bg-zinc-50 text-zinc-600"),
  },
  {
    id: "repair-pdf",
    titleKey: "tools.repairPdf.title",
    descriptionKey: "tools.repairPdf.description",
    icon: "build",
    href: "/repair-pdf",
    category: "edit",
    color: icon("bg-orange-50 text-orange-600"),
  },
  {
    id: "fill-pdf-forms",
    titleKey: "tools.fillPdfForms.title",
    descriptionKey: "tools.fillPdfForms.description",
    icon: "edit_note",
    href: "/fill-pdf-forms",
    category: "edit",
    color: icon("bg-cyan-50 text-cyan-600"),
  },
  {
    id: "grayscale-pdf",
    titleKey: "tools.grayscalePdf.title",
    descriptionKey: "tools.grayscalePdf.description",
    icon: "tonality",
    href: "/grayscale-pdf",
    category: "edit",
    color: icon("bg-neutral-50 text-neutral-600"),
  },
  {
    id: "invert-pdf",
    titleKey: "tools.invertPdf.title",
    descriptionKey: "tools.invertPdf.description",
    icon: "invert_colors",
    href: "/invert-pdf",
    category: "edit",
    color: icon("bg-purple-50 text-purple-600"),
  },
  {
    id: "flatten-pdf",
    titleKey: "tools.flattenPdf.title",
    descriptionKey: "tools.flattenPdf.description",
    icon: "layers",
    href: "/flatten-pdf",
    category: "edit",
    color: icon("bg-teal-50 text-teal-600"),
  },
  {
    id: "remove-annotations",
    titleKey: "tools.removeAnnotations.title",
    descriptionKey: "tools.removeAnnotations.description",
    icon: "comments_disabled",
    href: "/remove-annotations",
    category: "edit",
    color: icon("bg-rose-50 text-rose-600"),
  },
  {
    id: "add-image-pdf",
    titleKey: "tools.addImagePdf.title",
    descriptionKey: "tools.addImagePdf.description",
    icon: "add_photo_alternate",
    href: "/add-image-pdf",
    category: "edit",
    color: icon("bg-pink-50 text-pink-600"),
  },
  {
    id: "resize-pdf",
    titleKey: "tools.resizePdf.title",
    descriptionKey: "tools.resizePdf.description",
    icon: "aspect_ratio",
    href: "/resize-pdf",
    category: "edit",
    color: icon("bg-cyan-50 text-cyan-600"),
  },
  {
    id: "n-up-pdf",
    titleKey: "tools.nUpPdf.title",
    descriptionKey: "tools.nUpPdf.description",
    icon: "grid_view",
    href: "/n-up-pdf",
    category: "organize",
    color: icon("bg-violet-50 text-violet-600"),
  },
  {
    id: "booklet-pdf",
    titleKey: "tools.bookletPdf.title",
    descriptionKey: "tools.bookletPdf.description",
    icon: "menu_book",
    href: "/booklet-pdf",
    category: "organize",
    color: icon("bg-amber-50 text-amber-600"),
  },
  {
    id: "sanitize-pdf",
    titleKey: "tools.sanitizePdf.title",
    descriptionKey: "tools.sanitizePdf.description",
    icon: "cleaning_services",
    href: "/sanitize-pdf",
    category: "security",
    color: icon("bg-slate-50 text-slate-600"),
  },
  {
    id: "compress-images-pdf",
    titleKey: "tools.compressImagesPdf.title",
    descriptionKey: "tools.compressImagesPdf.description",
    icon: "photo_size_select_small",
    href: "/compress-images-pdf",
    category: "edit",
    color: icon("bg-emerald-50 text-emerald-600"),
  },
  // Security
  {
    id: "protect-pdf",
    titleKey: "tools.protectPdf.title",
    descriptionKey: "tools.protectPdf.description",
    icon: "lock",
    href: "/protect-pdf",
    category: "security",
    color: icon("bg-red-50 text-red-600"),
  },
  {
    id: "unlock-pdf",
    titleKey: "tools.unlockPdf.title",
    descriptionKey: "tools.unlockPdf.description",
    icon: "lock_open",
    href: "/unlock-pdf",
    category: "security",
    color: icon("bg-green-50 text-green-600"),
  },
  {
    id: "verify-signature-pdf",
    titleKey: "tools.verifySignaturePdf.title",
    descriptionKey: "tools.verifySignaturePdf.description",
    icon: "verified_user",
    href: "/verify-signature-pdf",
    category: "security",
    color: icon("bg-red-50 text-red-600"),
  },
];

export const CATEGORY_KEYS: { id: ToolCategory | "all"; labelKey: string }[] = [
  { id: "all", labelKey: "categories.all" },
  { id: "organize", labelKey: "categories.organize" },
  { id: "convert", labelKey: "categories.convert" },
  { id: "edit", labelKey: "categories.edit" },
  { id: "security", labelKey: "categories.security" },
];

export const CATEGORY_ORDER: ToolCategory[] = ["organize", "convert", "edit", "security"];

// Keep backward-compatible export name
export const CATEGORIES = CATEGORY_KEYS;
